version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-{{ checksum "build.gradle" }}
      - run: gradle assemble
      - run: gradle run 

workflows:
  version: 2
  workflow:
    jobs:
      - build