version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout     
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn package

workflows:
  version: 2
  workflow:
    jobs:
      - build